### ISSUE TITLE
Share via email target="_blank" is cause blank tab

### ISSUE THREAD

**Issue by salcode** [robincornett/scriptless-social-sharing#12]
On a Mac running Chrome v68, when I click the button to share via email.  A new tab opens in addition to the Apple Mail client opening to send an email.

Perhaps the share via email button would be better without the `target="_blank"` attribute?

**Comment by salcode** [comment]
FYI, I was able to solve this with the `` filter ( thank you for the filter 😀 ) but I still think it is worth considering whether the email share would be better off without this attribute.

```
/**
 * Remove target="_blank" from the Scriptless Social Sharing email share button.
 */
add_filter( 'scriptlesssocialsharing_link_markup', function( $markup, $button ) {
	if ( 'email' !== $button['name'] ) {
		return $markup;
	}
	return str_replace( ' target="_blank"', '', $markup );
}, 10, 2 );
```

**Comment by robincornett** [comment]
Thanks for pointing this out, Sal--I've updated the plugin code.

**Comment by salcode** [comment]
Thanks @robincornett, you rock!
