### ISSUE TITLE
Upgrade requires re-saving settings page?

### ISSUE THREAD

**Issue by salcode** [robincornett/scriptless-social-sharing#13]
I just upgraded from `v2.3.0` to `v3.0.1` via WP CLI.

When I then visited my site the share buttons were missing.

Going to the Scriptless Social Sharing Settings page (`/wp-admin/options-general.php?page=scriptlesssocialsharing`) and clicking `Save Changes` brought the share buttons back - there were no instructions to do this, it was just a lucky guess.

**Comment by robincornett** [comment]
Hi Sal, my guess is that your settings were saved in version 1.x of the plugin. Changes to how the button locations were set were introduced in version 2.0, and updating the settings was recommended at that time ([see the note here](https://github.com/robincornett/scriptless-social-sharing#what-if-i-want-to-move-where-the-buttons-are-output)). There was a fallback in version 2.x for it, but yes, that was removed in 3. I expect you may not be the only person to experience this, but checking/updating settings should resolve it--and some of the new options are worth checking out anyway, I think.
