### ISSUE TITLE
rawurlencode permalinks when adding to share links

### ISSUE THREAD

**Issue by salcode** [robincornett/scriptless-social-sharing#6]
In #4, I talk about a filter to modify the permalink being shared, which I still think is a good idea.  Playing with this idea surfaced the behavior that if you have more than one URL parameter on the link being shared, it is not passed through properly (at least not to Twitter).

## How to Recreate the Issue

Add the following code in a mu-plugin.  This code modifies all post permalinks (everywhere on the site) to include `?utm_source=salcodecom&utm_medium=blogpost`.  This include the permalinks within the share button.

```
add_filter( 'post_link', 'fe_demo_add_query_param_to_post_urls' );

function fe_demo_add_query_param_to_post_urls( $url ) {
	return add_query_arg( array(
		'utm_source' => 'salcodecom',
		'utm_medium' => 'blogpost',
	), $url );
}
```

### What I Expected

I expected the twitter share box to come up populated with

```
test http://salferrarello.dev/test/?utm_source=salcodecom&utm_medium=blogpost via @salcode
```

### What Actually Happened

The twitter share box was populated with 

```
test http://salferrarello.dev/test/?utm_source=salcodecom via @salcode
```

You can see the `&utm_medium=blogpost` from the URL to be shared is missing.

## The fix

We can correct this by urlencoding the URL.

### Current Share URL

```
https://twitter.com/intent/tweet?text=test&#038;url=http://salferrarello.dev/test/?utm_source=salcodecom&#038;utm_medium=blogpost&#038;via=salcode&#038;related=salcode
```

### Desired Share URL

```
https://twitter.com/intent/tweet?text=test&#038;url=http%3A%2F%2Fsalferrarello.dev%2Ftest%2F%3Futm_source%3Dsalcodecom%26utm_medium%3Dblogpost&#038;via=salcode&#038;related=salcode
```

We can do this by wrapping `$attributes['permalink']` in `rawurlencode()` on each of the lines where we make the buttons e.g. [includes/class-scriptlesssocialsharing-output.php](https://github.com/robincornett/scriptless-social-sharing/blob/develop/includes/class-scriptlesssocialsharing-output.php#L167)

```
$buttons['twitter']['url']   = sprintf( 'https://twitter.com/intent/tweet?text=%s&url=%s%s', $twitter_title, $attributes['permalink'], $attributes['twitter'] );
```

becomes

```
$buttons['twitter']['url']   = sprintf( 'https://twitter.com/intent/tweet?text=%s&url=%s%s', $twitter_title, rawurlencode( $attributes['permalink'] ), $attributes['twitter'] );
```

However rather than doing this on each line, if we add the `get_permalink()` method in Pull Request #5 we can then add `rawurlencode()` once in that method.

So 

		return apply_filters( 'scriptlesssocialsharing_get_permalink',
			$attributes['permalink'],
			$button_name,
			$attributes
		);

becomes

		return rawurlencode(
			apply_filters( 'scriptlesssocialsharing_get_permalink',
				$attributes['permalink'],
				$button_name,
				$attributes
			)
		);

**Comment by robincornett** [comment]
This makes sense to me. I'm pondering a fairly significant overhaul (if I can make it backwards compatible) and you bringing this up makes me think I should revisit how I've built the URLs in the first place, if I should use `add_query_arg` to make them happen, which might affect your PR, I think?

**Comment by salcode** [comment]
I imagine significant changes will affect the PR.  My vote would be get this in place and then refactor.

One refactoring thought I had was moving all of the work in [lines 167-174](https://github.com/robincornett/scriptless-social-sharing/blob/develop/includes/class-scriptlesssocialsharing-output.php#L167-L174) into the `get_permlink()` method I created but I that seems like a bigger refactor than I wanted to introduce in this PR.
